### ISSUE TITLE
HaxeDevelop wont shut up about "missing" libraries.

### ISSUE THREAD

**Issue by modjke** [fdorg/flashdevelop#1588]
This is annoying as hell:
I have a big project with a lot of dependencies (mostly git lib version), setuped as Custom Build with single hxml.
Almost every time i open .hx file / build a project haxedevelop opens modal window saying that
'missing libraries detected, would you like to install em?'
even there are no libraries missing.

Latest development build of haxedevelop (@win7/10) with haxe 3.4.2

**Comment by SlavaRa** [comment]
I will create PR today after the main work

**Comment by Neverbirth** [comment]
I pushed some fix for cases where missing libraries where reported after installing them.

**Comment by Tembac** [comment]
The same happens to me when I'm building the project for android with several openfl extensions. It is annoying because a lot of signs appear but the project is compiling fine.

**Comment by pozirk** [comment]
Same here, but with FlashDevelop.
Anyone could solve this?

**Comment by AdamHarte** [comment]
Seems like this is still a problem with me building on Android. Doesn't seem to cause any issues. Just shows an annoying dialog every time I build.

**Comment by SlavaRa** [comment]
Can you test development-build from http://flashdevelop.org/downloads/builds/ ?

**Comment by PaulGene** [comment]
I'm still getting this issue when building for Android with OpenFL.  Tried the 01/02/19 dev build and it has the same problem.
