### ISSUE TITLE
[Bug][Debug] Internal Debugger Exception

### ISSUE THREAD

**Issue by benjstern** [fdorg/flashdevelop#1898]
![image](https://user-images.githubusercontent.com/1266727/34554832-8c7ee2c8-f137-11e7-995d-a1a812d40a4b.png)

Nothing is sent to the output when I check the exeptions.log I get:

2018-01-04 10:03:01 AM

Internal Debugger Exception

System.NullReferenceException: Object reference not set to an instance of an object.
   at net.sf.jni4net.jni.JNIEnv.CallStaticObjectMethodPtr(Class clazz, MethodId methodIdNative, Value[] args)
   at flash.tools.debugger.Bootstrap.sessionManager()
   at FlashDebugger.FlashInterface.Start()
   at FlashDebugger.DebuggerManager.bgWorker_DoWork(Object sender, DoWorkEventArgs e)

At first run the application works and debugs fine, at subsequent runs it's shows this error message.

I'm running FlashDevelop 5.3.1.67 Development version.

Originally thought it was related to this: https://github.com/fdorg/flashdevelop/issues/1855, but upon further investigation seems to be a separate issue.

**Comment by benjstern** [comment]
Same with Development version 5.3.1.67

Debugger startup error. For troubleshooting see: http://www.flashdevelop.org/wikidocs/index.php?title=F.A.Q
Error details: net.sf.jni4net.jni.JNIException: Can't load java class for flash.tools.debugger.concrete.DValue_ from classLoader sun.misc.Launcher$AppClassLoader@757aef ---> java.lang.LinkageError: flash/tools/debugger/concrete/DValue_ : Unsupported major.minor version 52.0
at net.sf.jni4net.jni.JNIEnv.ExceptionTest()
at net.sf.jni4net.jni.JNIEnv.CallObjectMethodPtr(IJvmProxy obj, MethodId methodIdNative, Value[] args)
at java.lang.ClassLoader.loadClass(String par0)
at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
--- End of inner exception stack trace ---
at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
at net.sf.jni4net.utils.Registry.RegisterClass(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
at net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
at net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
at net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
at FlashDebugger.DebuggerManager.Start(Boolean alwaysStart)

**Comment by Neverbirth** [comment]
Maybe this is fixed or improved in https://ci.appveyor.com/api/buildjobs/pb46pxtxd6362jce/artifacts/FlashDevelop%2FInstaller%2FBinary%2FFlashDevelopPR_1956.zip

**Comment by ghost** [comment]
Same with 5.3.1.27

Debugger startup error. For troubleshooting see: http://www.flashdevelop.org/wikidocs/index.php?title=F.A.Q
Error details: net.sf.jni4net.jni.JNIException: Can't load java class for flash.tools.debugger.concrete.DValue_ from classLoader sun.misc.Launcher$AppClassLoader@35ce36 ---> java.lang.LinkageError: flash/tools/debugger/concrete/DValue_ : Unsupported major.minor version 52.0
   at net.sf.jni4net.jni.JNIEnv.ExceptionTest()
   at net.sf.jni4net.jni.JNIEnv.CallObjectMethodPtr(IJvmProxy obj, MethodId methodIdNative, Value[] args)
   at java.lang.ClassLoader.loadClass(String par0)
   at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   --- End of inner exception stack trace ---
   at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterClass(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
   at net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
   at FlashDebugger.DebuggerManager.Start(Boolean alwaysStart)
[Capturing traces with FDB]

**Comment by ghost** [comment]
Same with 5.3.1.27 and with 5.3 (the latest as of 15 Mar 2018)

FD x32 and Java 1.6 x32.

> Debugger startup error. For troubleshooting see: http://www.flashdevelop.org/wikidocs/index.php?title=F.A.Q
> Error details: net.sf.jni4net.jni.JNIException: **Can't load java class for flash.tools.debugger.concrete.DValue_** from classLoader sun.misc.Launcher$AppClassLoader@35ce36 ---> java.lang.LinkageError: flash/tools/debugger/concrete/DValue_ : Unsupported major.minor version 52.0
>    at net.sf.jni4net.jni.JNIEnv.ExceptionTest()
>    at net.sf.jni4net.jni.JNIEnv.CallObjectMethodPtr(IJvmProxy obj, MethodId methodIdNative, Value[] args)
>    at java.lang.ClassLoader.loadClass(String par0)
>    at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
>    --- End of inner exception stack trace ---
>    at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
>    at net.sf.jni4net.utils.Registry.RegisterClass(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
>    at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
>    at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
>    at net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
>    at net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
>    at net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
>    at FlashDebugger.DebuggerManager.Start(Boolean alwaysStart)
> [Capturing traces with FDB]

If I use FD x64, I get this

> Debugger startup error. For troubleshooting see: http://www.flashdevelop.org/wikidocs/index.php?title=F.A.Q
> Error details: net.sf.jni4net.jni.JNIException: Can't initialize jni4net. **(32bit vs 64bit JVM vs CLR ?)**
> CLR architecture: 64bit
> JAVA_HOME: C:\Program Files (x86)\Java\jre6\ ---> **System.BadImageFormatException: An attempt was made to load a program with an incorrect format**. (Exception from HRESULT: 0x8007000B)
>    at net.sf.jni4net.jni.JNI.Dll.JNI_GetDefaultJavaVMInitArgs(JavaVMInitArgs* args)
>    at net.sf.jni4net.jni.JNI.Init()
>    --- End of inner exception stack trace ---
>    at net.sf.jni4net.jni.JNI.Init()
>    at net.sf.jni4net.jni.JNI.CreateJavaVM(JavaVM& jvm, JNIEnv& env, Boolean attachIfExists, String[] options)
>    at net.sf.jni4net.Bridge.CreateJVM()
>    at net.sf.jni4net.Bridge.CreateJVM(BridgeSetup setup)
>    at FlashDebugger.DebuggerManager.Start(Boolean alwaysStart)
> [Capturing traces with FDB]
>

**Comment by benjamin-stern** [comment]
Yeah I'm still getting the same issues even after a clean install not sure what's going on with it cannot connect to the debugger.

**Comment by benjamin-stern** [comment]
When reverting back to 5.0.2 working fine with the same setup and environment variables.
