### ISSUE TITLE
Method call tip: pressing F1 twice removes the selected argument highlight

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#937]
1. Start writing some method call.  
   ![call-tip-1](http://i.imgur.com/ivgvH0a.png)
2. Press F1 to see details  
   ![call-tip-2](http://i.imgur.com/Fjgks9s.png)
3. Press F1 again  
   ![call-tip-3](http://i.imgur.com/6gUmPce.png)

Expected results: screenshots 1 and 3 should be the same
Actual results: the selected argument highlight has disappeared

**Comment by Neverbirth** [comment]
I have this fixed in one of my branches along with other fixes and improvements... as soon as I can I'll make a PR.

**Comment by gene-pavlovsky** [comment]
@Neverbirth great, looking forward!

**Comment by Neverbirth** [comment]
Since it's more or less related, I'm going to make some spam here... please, take a look at [this thread](http://flashdevelop.org/community/viewtopic.php?f=9&t=12472).

**Comment by gene-pavlovsky** [comment]
Hey @Neverbirth, I can still see this issue in FD 5.1.1. Were your fixes ever merged?

**Comment by gene-pavlovsky** [comment]
@Neverbirth I guess that your fixes are still not merged, because I can still reproduce this issue
